---
name: automerge
on:
  workflow_run:
    types:
      - completed
    workflows:
      - "ci"
jobs:
  check-mergeability:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.actor == 'nsmbot' }}
    uses: networkservicemesh/.github/.github/workflows/check-mergeability.yaml@main
    secrets:
      token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}

  automerge:
    needs: [check-mergeability]
    uses: networkservicemesh/.github/.github/workflows/automerge.yaml@main

  resolve_conflicts:
    needs: [check-mergeability]
    if: ${{ always() && needs.check-mergeability.result == 'failure' && needs.check-mergeability.outputs.pr_branch_ref != '' }}
    uses: networkservicemesh/.github/.github/workflows/check-mergeability.yaml@main
    with:
      pr_branch_ref: ${{ needs.check-mergeability.outputs.pr_branch_ref }}
    secrets:
      token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
